import { IGRPMenuItemArgs } from '@igrp/framework-next-types';

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = [
  {
    id: 6,
    name: 'Settings',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/system-settings',
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },
  {
    id: 7,
    name: 'Dashboard',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/dashboard',
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },
  {
    id: 8,
    name: 'Configuração',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/processconfiguration',
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },
  {
    id: 9,
    name: 'Mapa Processos',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/processmap',
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },
  {
    id: 10,
    name: 'Tarefas Disponiveis',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/availabletasks',
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },
  {
    id: 11,
    name: 'Processos',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/processinstances',
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },
  {
    id: 12,
    name: 'Minhas Tarefas',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/mytasks',
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },
  {
    id: 13,
    name: 'Gestão de Tarefas',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    target: 'INTERNAL',
    url: '/taskmanagement',
    parentId: null,
    applicationId: 1,
    resourceId: null,
  },
];
