import { IGRPMenuItemArgs } from "@igrp/framework-next-types";

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = [
  {
    id: 7,
    name: "Dashboard",
    type: "MENU_PAGE",
    position: 1,
    icon: "LayoutDashboard",
    status: "ACTIVE",
    target: "_self",
    url: "/",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_1",
  },
  {
    id: 8,
    name: "Configuração",
    type: "MENU_PAGE",
    position: 1,
    icon: "Settings2",
    status: "ACTIVE",
    target: "_self",
    url: "/processconfiguration",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_2",
  },
  {
    id: 9,
    name: "Mapa Processos",
    type: "MENU_PAGE",
    position: 1,
    icon: "Workflow",
    status: "ACTIVE",
    target: "_self",
    url: "/processmap",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_3",
  },
  {
    id: 10,
    name: "Tarefas Disponiveis",
    type: "MENU_PAGE",
    position: 1,
    icon: "Settings2",
    status: "ACTIVE",
    target: "_self",
    url: "/availabletasks",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_4",
  },
  {
    id: 11,
    name: "Processos",
    type: "MENU_PAGE",
    position: 1,
    icon: "Settings2",
    status: "ACTIVE",
    target: "_self",
    url: "/processinstances",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_5",
  },
  {
    id: 12,
    name: "Minhas Tarefas",
    type: "MENU_PAGE",
    position: 1,
    icon: "UserLock",
    status: "ACTIVE",
    target: "_self",
    url: "/mytasks",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_6",
  },
  {
    id: 13,
    name: "Gestão de Tarefas",
    type: "MENU_PAGE",
    position: 1,
    icon: "Settings2",
    status: "ACTIVE",
    target: "_self",
    url: "/taskmanagement",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_7",
  },
];
