import { IGRPMenuItemArgs } from "@igrp/framework-next-types";

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = [
  {
    id: 7,
    name: "Dashboard",
    type: "MENU_PAGE",
    position: 1,
    icon: "LayoutDashboard",
    status: "ACTIVE",
    target: "_self",
    url: "/",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_1",
  },
  {
    id: 8,
    name: "Configuração",
    type: "MENU_PAGE",
    position: 2,
    icon: "Settings2",
    status: "ACTIVE",
    target: "_self",
    url: "/process-configuration",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_2",
  },
  {
    id: 1,
    name: "Configuração de Processos",
    type: "MENU_PAGE",
    position: 2,
    icon: "Settings2",
    status: "ACTIVE",
    target: "_self",
    url: "/config",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_2",
  },
  {
    id: 9,
    name: "Mapa Processos",
    type: "MENU_PAGE",
    position: 3,
    icon: "Workflow",
    status: "ACTIVE",
    target: "_self",
    url: "/process-map",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_3",
  },
  {
    id: 10,
    name: "Tarefas Disponiveis",
    type: "MENU_PAGE",
    position: 5,
    icon: "Settings2",
    status: "ACTIVE",
    target: "_self",
    url: "/available-tasks",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_4",
  },
  {
    id: 11,
    name: "Processos",
    type: "MENU_PAGE",
    position: 7,
    icon: "Activity",
    status: "ACTIVE",
    target: "_self",
    url: "/process-instances",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_5",
  },
  {
    id: 5,
    name: "Minhas Tarefas",
    type: "MENU_PAGE",
    position: 4,
    icon: "UserLock",
    status: "ACTIVE",
    target: "_self",
    url: "/my-tasks",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_6",
  },
  {
    id: 13,
    name: "Gestão de Tarefas",
    type: "MENU_PAGE",
    position: 6,
    icon: "Settings2",
    status: "ACTIVE",
    target: "_self",
    url: "/task-management",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
    code: "MENU_PAGE_7",
  },
];
