import { IGRPApplicationArgs } from '@igrp/framework-next-types';

export const IGRP_MOCK_APPS_DATA: IGRPApplicationArgs[] = [
  // {
  //   id: 1,
  //   code: "APP_IGRP",
  //   name: "iGRP",
  //   description: "iGRP Application",
  //   status: "ACTIVE",
  //   type: "INTERNAL",
  //   owner: "superadmin",
  //   picture: null,
  //   url: null,
  //   slug: null ,
  //   departmentCode: "DEPT_IGRP"
  // },
  {
    id: 35,
    code: 'APP_TEST_1',
    name: 'test 1',
    description: null,
    status: 'ACTIVE',
    type: 'INTERNAL',
    owner: 'superadmin',
    picture: '',
    url: null,
    slug: 'test-1',
    departmentCode: 'DEPT_IGRP',
  },
  {
    id: 36,
    code: 'APP_TESTE_2',
    name: 'test 2',
    description: 'teste app ',
    status: 'ACTIVE',
    type: 'INTERNAL',
    owner: 'superadmin',
    picture: '',
    url: null,
    slug: 'test-2',
    departmentCode: 'DEPT_IGRP',
  },
  {
    id: 34,
    code: 'APP_CODE',
    name: 'qqqqqqq',
    description: 'teste app qqqqqq',
    status: 'ACTIVE',
    type: 'INTERNAL',
    owner: 'superadmin',
    picture: '',
    url: null,
    slug: 'qqqqqqq',
    departmentCode: 'DEPT_IGRP',
  },
];
